/***
 * midj.js for Image Prompter
 * Integrate with Midjourney workspace, including discord or others.
 * 1）Two-way control Midjourney prompt textbox, set or get prompt.
 * 2) Implement collect function: Collect images generated by Midjourney to Image Prompter collection.
 * 
 * author: Ray Lee
 * studio: Luupine
 * website: https://sites.google.com/view/imageprompter
 * emmail: raykkncc@gmail.com
 * date: 2023-5-20
 * Note: Third party library JQuery is used (version 3.6.4).
 *       This javascript file should be run in extension environment. Included in main.html or other html files.
 */

/*
function setMidjPrompt( new_prompt ) {
    let prompt_box = null; 
    console.log('parent 1st child ' + parent.document.firstChild.nodeName );
    prompt_box = parent.document.querySelectorAll(`span[data-slate-string=true]`);
   
    console.log( 'prompt_box.length ' + prompt_box.length );
    if( prompt_box.length > 0  ) {
        console.log( prompt_box[0].innerText  );
        console.log('Current prompt: ' + prompt_box[0].innerText );
        prompt_box[0].innerText = new_prompt ;
    }
    
}
*/